### ISSUE TITLE
Withdraw operation throws error

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-SupalukBenz#1]
Steps:
1. Deposit: `10` `5` `2` ✅
3. Check balance:  `Purse contains 17.00 Baht` ✅
2. Withdraw: `7` ❌
```
Exception in thread "main" java.lang.NullPointerException
	at coinpurse.ConsoleDialog.withdrawDialog(ConsoleDialog.java:118)
	at coinpurse.ConsoleDialog.run(ConsoleDialog.java:53)
	at coinpurse.Main.main(Main.java:20)
```

**Comment by kykungz** [comment]
My fault.

**Comment by supalukbenz** [comment]
<img width="486" alt="screen shot 2561-01-22 at 19 07 47" src="https://user-images.githubusercontent.com/32286346/35220079-93da2e8c-ffa7-11e7-9740-90a13f343580.png">
